version: '3.8'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local-skypal
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath .'
    ports:
      - '8000:8000'